# Generated by Django 4.1.7 on 2023-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sichleyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionname', models.CharField(max_length=333)),
                ('countyname', models.CharField(max_length=233)),
                ('subcountyname', models.CharField(max_length=233)),
                ('wardname', models.CharField(max_length=233)),
            ],
        ),
    ]
