# Generated by Django 4.1.7 on 2023-03-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sichleyapp', '0003_land_rename_member_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='ward_name',
        ),
    ]
